# NUMPY
## 1. Few commonly used methods

In [1]:
import numpy as np

In [2]:
my_list = [[1,2,3],[4,5,6],[9,10,11]]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### IDENTITY MATRIX

In [8]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### ARRAY OF RANDOM NUMBERS

In [9]:
# populate uniform distribution from 0 to 1
np.random.rand()

0.980776596370242

In [10]:
# uniform standard distribution centered on 0 (-1-0-1)
np.random.randn()

-0.9281647453221904

In [11]:
# randint(lo,hi,n): return n random integer(s) from lo (inclusive) to hi (exclusive)
np.random.randint(1,100,5)

array([49, 10, 42, 66, 98])

## 2. Few useful methods & attributes of numpy array

In [12]:
from numpy.random import randint
arr = np.arange(25)
ranarr = randint(0,50,10)

#### Reshaping Array Method

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Finding min/max values

In [14]:
ranarr.min()

3

In [15]:
ranarr.max()

47

#### Return Element Position in the Array

In [16]:
ranarr.argmin()

4

In [17]:
ranarr.argmax()

7

#### Return the Vector Shape Information

In [18]:
arr.shape

(25,)

arr is one dimensional. Now:

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.shape

(25,)

#### Data Type in the Array

In [21]:
arr.dtype

dtype('int32')

## 3. Indexing and Selection

In [24]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[:5]

array([0, 1, 2, 3, 4])

In [27]:
arr[2:6]

array([2, 3, 4, 5])

In [28]:
arr[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Broadcast Ability

In [29]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [30]:
slice_of_arr = arr[0:6]

In [31]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [32]:
slice_of_arr[:] = 90
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [33]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Note that the original array variable "arr" is changed as well and not only the sliced array "slice_of_arr". This is because numpy wants to avoid memory issues for very large arrays case. <br>
To keep original array, use <b> .copy() </b> feature

#### .copy() Method to keep original array

In [34]:
arr_copy = arr.copy()

In [35]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arr_copy

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [38]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 2D Array (Matrix) Indexing

In [39]:
arr_2d = np.array([[5,10,15],[20,25,30],[50,55,60]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 55, 60]])

#### Double-Bracket Format Notation

In [41]:
arr_2d[0][1]

10

In [42]:
arr_2d[1]

array([20, 25, 30])

In [43]:
arr_2d[2][2]

60

Meh, too dirty eh

#### Single-Bracket Format Common Notation

In [44]:
arr_2d[2,2]

60

In [45]:
arr_2d[0,1]

10

### Grab Chunks of Array Elements

Use colon and comma

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 55, 60]])

In [46]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Grab everything below row 2 but not including row 2, then grab column 1 and above all the way to the end

In [48]:
arr_2d[1:]

array([[20, 25, 30],
       [50, 55, 60]])

In [51]:
arr_2d[0:,1:]

array([[10, 15],
       [25, 30],
       [55, 60]])

In [54]:
arr_2d[0,0]

5

In [55]:
arr_2d[0:,0]

array([ 5, 20, 50])

### Conditional Selection

In [56]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
bool_arr = arr > 5

In [59]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>7]

array([ 8,  9, 10])

In [64]:
arr[arr<3]

array([1, 2])

## 4. Closure

In [66]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [68]:
arr_2d[1:3, 4:8]

array([[14, 15, 16, 17],
       [24, 25, 26, 27]])