# NumPy Lecture Scrapnote
___

Documentation Page: [NumPy](https://numpy.org/doc/stable/)
___

## 1. Few commonly used methods

In [1]:
import numpy as np

In [2]:
my_list = [[1,2,3],[4,5,6],[9,10,11]]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### IDENTITY MATRIX

In [8]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### ARRAY OF RANDOM NUMBERS

In [9]:
# populate uniform distribution from 0 to 1
np.random.rand()

0.6903112767075578

In [10]:
# uniform standard distribution centered on 0 (-1-0-1)
np.random.randn()

0.2741469731084723

In [11]:
# randint(lo,hi,n): return n random integer(s) from lo (inclusive) to hi (exclusive)
np.random.randint(1,100,5)

array([92, 34, 32,  5, 40])

## 2. Few useful methods & attributes of numpy array

In [12]:
from numpy.random import randint
arr = np.arange(25)
ranarr = randint(0,50,10)

#### Reshaping Array Method

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Finding min/max values

In [14]:
ranarr.min()

3

In [15]:
ranarr.max()

41

#### Return Element Position in the Array

In [16]:
ranarr.argmin()

9

In [17]:
ranarr.argmax()

5

#### Return the Vector Shape Information

In [18]:
arr.shape

(25,)

arr is one dimensional. Now:

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.shape

(25,)

#### Data Type in the Array

In [21]:
arr.dtype

dtype('int32')

## 3. Indexing and Selection

In [22]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [24]:
arr[:5]

array([0, 1, 2, 3, 4])

In [25]:
arr[2:6]

array([2, 3, 4, 5])

In [26]:
arr[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Broadcast Ability

In [27]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [28]:
slice_of_arr = arr[0:6]

In [29]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [30]:
slice_of_arr[:] = 90
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [31]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Note that the original array variable "arr" is changed as well and not only the sliced array "slice_of_arr". This is because numpy wants to avoid memory issues for very large arrays case. <br>
To keep original array, use <b> .copy() </b> feature

#### .copy() Method to keep original array

In [32]:
arr_copy = arr.copy()

In [33]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
arr_copy

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [36]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 2D Array (Matrix) Indexing

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[50,55,60]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 55, 60]])

#### Double-Bracket Format Notation

In [38]:
arr_2d[0][1]

10

In [39]:
arr_2d[1]

array([20, 25, 30])

In [40]:
arr_2d[2][2]

60

Meh, too dirty eh

#### Single-Bracket Format Common Notation

In [41]:
arr_2d[2,2]

60

In [42]:
arr_2d[0,1]

10

### Grab Chunks of Array Elements

Use colon and comma

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 55, 60]])

In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Grab everything below row 2 but not including row 2, then grab column 1 and above all the way to the end

In [45]:
arr_2d[1:]

array([[20, 25, 30],
       [50, 55, 60]])

In [46]:
arr_2d[0:,1:]

array([[10, 15],
       [25, 30],
       [55, 60]])

In [47]:
arr_2d[0,0]

5

In [48]:
arr_2d[0:,0]

array([ 5, 20, 50])

### Conditional Selection

In [49]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
bool_arr = arr > 5

In [52]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [54]:
arr[arr>7]

array([ 8,  9, 10])

In [55]:
arr[arr<3]

array([1, 2])

### Closure for 3rd part

In [56]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
arr_2d[1:3, 4:8]

array([[14, 15, 16, 17],
       [24, 25, 26, 27]])

## 4. Numpy Operations

Any basic arithmetic works. As in any other problem of your life yeah...

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [63]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [66]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [67]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [71]:
arr / arr

<ipython-input-71-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
1 / arr

<ipython-input-72-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [73]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [76]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [77]:
np.max(arr)

10

In [78]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [79]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [80]:
np.log(arr)

<ipython-input-80-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

<b>FINISHED